stages:
  data_ingestion:
    cmd: python src/deepClassifier/pipeline/STAGE_1_data_ingestion.py
    deps:
      - src/deepClassifier/pipeline/STAGE_1_data_ingestion.py
      - configs/config.yaml
    outs:
      - artifacts/data_ingestion/PetImages


  prepare_base_model:
    cmd: python src/deepClassifier/pipeline/STAGE_2_prepare_base_model.py
    deps:
      - src/deepClassifier/pipeline/STAGE_2_prepare_base_model.py
      - configs/config.yaml
    params:
      - IMAGE_SIZE
      - INCLUDE_TOP
      - CLASSES
      - WEIGHTS
      - LEARNING_RATE
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/deepClassifier/pipeline/STAGE_3_prepare_call_back.py
    deps:
      - src/deepClassifier/pipeline/STAGE_3_prepare_call_back.py
      - src/deepClassifier/components/prepare_callbacks.py
      - configs/config.yaml
      - artifacts/prepare_base_model
      - artifacts/data_ingestion/PetImages
    params:
      - IMAGE_SIZE
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
    outs:
      - artifacts/training/model.h5